name: ci

on:
  push:
    branches:
    - main
    - test-me-*
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

env:
  LANG: en_US.utf-8
  LC_ALL: en_US.utf-8
  PYTHONIOENCODING: UTF-8
  PYTHONWARNDEFAULTENCODING: "1"
  PYTHON_VERSIONS: ""

jobs:

  quality:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        python-version:
        - "3.9"
        - "3.13"
        include:
        - os: ubuntu-latest
          python-version: "3.10"
        - os: ubuntu-latest
          python-version: "3.11"
        - os: ubuntu-latest
          python-version: "3.12"

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: pyproject.toml

    - name: Install dependencies
      run: make setup

    - name: Check if the documentation builds correctly
      run: make check-docs

    - name: Check the code quality
      run: make check-quality

    - name: Check if the code is correctly typed
      run: make check-types

    - name: Check for breaking changes in the API
      run: make check-api

    - name: Store objects inventory for tests
      uses: actions/upload-artifact@v4
      with:
        name: objects.inv
        path: site/objects.inv

  tests:

    needs:
    - quality
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        python-version:
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
        - "3.14"
        resolution:
        - highest
        - lowest-direct
        exclude:
        - os: macos-latest
          resolution: lowest-direct
        - os: windows-latest
          resolution: lowest-direct
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - name: Setup uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: pyproject.toml
        cache-suffix: ${{ matrix.resolution }}

    - name: Install dependencies
      env:
        UV_RESOLUTION: ${{ matrix.resolution }}
      run: make setup

    - name: Download objects inventory
      uses: actions/download-artifact@v4
      with:
        name: objects.inv
        path: site/

    - name: Run the test suite
      run: make test
